//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoxOfficeDto", Namespace="http://schemas.datacontract.org/2004/07/Cingulariti.ANDROMEDA.Business")]
    [System.SerializableAttribute()]
    public partial class BoxOfficeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Testing.ServiceReference.MovieDto[] MoviesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResultsDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Testing.ServiceReference.MovieDto[] Movies {
            get {
                return this.MoviesField;
            }
            set {
                if ((object.ReferenceEquals(this.MoviesField, value) != true)) {
                    this.MoviesField = value;
                    this.RaisePropertyChanged("Movies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResultsDate {
            get {
                return this.ResultsDateField;
            }
            set {
                if ((this.ResultsDateField.Equals(value) != true)) {
                    this.ResultsDateField = value;
                    this.RaisePropertyChanged("ResultsDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieDto", Namespace="http://schemas.datacontract.org/2004/07/Cingulariti.ANDROMEDA.Business")]
    [System.SerializableAttribute()]
    public partial class MovieDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DailyGrossField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PercentChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TheatersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalGrossField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Average {
            get {
                return this.AverageField;
            }
            set {
                if ((this.AverageField.Equals(value) != true)) {
                    this.AverageField = value;
                    this.RaisePropertyChanged("Average");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DailyGross {
            get {
                return this.DailyGrossField;
            }
            set {
                if ((this.DailyGrossField.Equals(value) != true)) {
                    this.DailyGrossField = value;
                    this.RaisePropertyChanged("DailyGross");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayNumber {
            get {
                return this.DayNumberField;
            }
            set {
                if ((this.DayNumberField.Equals(value) != true)) {
                    this.DayNumberField = value;
                    this.RaisePropertyChanged("DayNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PercentChange {
            get {
                return this.PercentChangeField;
            }
            set {
                if ((this.PercentChangeField.Equals(value) != true)) {
                    this.PercentChangeField = value;
                    this.RaisePropertyChanged("PercentChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Studio {
            get {
                return this.StudioField;
            }
            set {
                if ((object.ReferenceEquals(this.StudioField, value) != true)) {
                    this.StudioField = value;
                    this.RaisePropertyChanged("Studio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Theaters {
            get {
                return this.TheatersField;
            }
            set {
                if ((this.TheatersField.Equals(value) != true)) {
                    this.TheatersField = value;
                    this.RaisePropertyChanged("Theaters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalGross {
            get {
                return this.TotalGrossField;
            }
            set {
                if ((this.TotalGrossField.Equals(value) != true)) {
                    this.TotalGrossField = value;
                    this.RaisePropertyChanged("TotalGross");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IBoxOffice")]
    public interface IBoxOffice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoxOffice/GetBoxOfficeResults", ReplyAction="http://tempuri.org/IBoxOffice/GetBoxOfficeResultsResponse")]
        Testing.ServiceReference.BoxOfficeDto GetBoxOfficeResults(System.DateTime resultsDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IBoxOfficeChannel : Testing.ServiceReference.IBoxOffice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BoxOfficeClient : System.ServiceModel.ClientBase<Testing.ServiceReference.IBoxOffice>, Testing.ServiceReference.IBoxOffice {
        
        public BoxOfficeClient() {
        }
        
        public BoxOfficeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BoxOfficeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoxOfficeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoxOfficeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Testing.ServiceReference.BoxOfficeDto GetBoxOfficeResults(System.DateTime resultsDate) {
            return base.Channel.GetBoxOfficeResults(resultsDate);
        }
    }
}
